@startuml
class Adapter extends Adaptee implements Target
Target : request()
Adaptee : specificRequest()
Adapter : request()

Client --> Target

note right of Adapter::request()
specificRequest();
end note
@enduml