@startuml
class ConcretePrototype1 implements Prototype
class ConcretePrototype2 implements Prototype
Prototype : clone()
ConcretePrototype1 : clone()
ConcretePrototype2 : clone()

Client --> Prototype
Client : operation()

note right of ConcretePrototype1::clone
return copy of self
end note

note right of ConcretePrototype2::clone
return copy of self
end note

note right of Client::operation
p = prototype.clone();
end note
@enduml