@startuml
class ConcreteComponent implements Component
class Decorator implements Component
Decorator *-- Component
Component : operation()
ConcreteComponent : operation()
Decorator : operation()

class ConcreteDecoratorA extends Decorator
class ConcreteDecoratorB extends Decorator
ConcreteDecoratorA : operation()
ConcreteDecoratorA : addedState
ConcreteDecoratorB : operation()
ConcreteDecoratorB : addedBehavior()

note right of Decorator::operation()
component.operation();
end note

note right of ConcreteDecoratorB::operation()
decorator.operation();
addedBehavior();
end note
@enduml